version: "3.4"
services:
  op25:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:8080" # Change this to reflect the http port being used.
    volumes:
      - ./config:/op25/op25/gr-op25_repeater/apps/config
    devices:
      - "/dev/bus/usb:/dev/bus/usb" # This may present security issues if you are worried about code breaking out of the container.
      - "/dev/snd"
